# Generated by Django 5.0.4 on 2024-05-04 13:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Страна'),
            preserve_default=False,
        ),
    ]
