# Generated by Django 5.0.4 on 2024-04-28 11:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date_of_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=100, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='image_preview',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='publication_sign',
            field=models.BooleanField(default=0, verbose_name='Публикации'),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='slug'),
        ),
    ]
