# Generated by Django 5.0.4 on 2024-04-29 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_date_of_creation_blog_image_preview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 29, 15, 4, 46, 45015), max_length=100, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_preview',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='publication_sign',
            field=models.BooleanField(default=True, verbose_name='Публикации'),
        ),
    ]
