# Generated by Django 5.0.4 on 2024-04-29 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_date_of_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 29, 15, 54, 23, 260002), max_length=100, verbose_name='Дата создания'),
        ),
    ]
