# Generated by Django 5.0.4 on 2024-04-29 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blog_date_of_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 29, 18, 7, 27, 184142), max_length=100, verbose_name='Дата создания'),
        ),
    ]
