# Generated by Django 5.0.4 on 2024-05-04 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blog_date_of_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 4, 15, 22, 10, 392348), max_length=100, verbose_name='Дата создания'),
        ),
    ]
