# Generated by Django 5.0.4 on 2024-04-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='наименование')),
                ('Description', models.TextField(max_length=100, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'наименование_категории',
                'verbose_name_plural': 'категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='наименование')),
                ('Description', models.TextField(max_length=100, verbose_name='описание')),
                ('image_preview', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('category', models.CharField(max_length=100, verbose_name='категория')),
                ('price_per_purchase', models.IntegerField(max_length=100, verbose_name='цена_за_покупку')),
                ('date_of_creation', models.DateTimeField(max_length=100, verbose_name='дата_создания_(записи_в_БД)')),
                ('date_of_last_change', models.DateTimeField(max_length=100, verbose_name='дата_последнего_изменения_(записи_в_БД)')),
            ],
            options={
                'verbose_name': 'наименование_продукта',
                'verbose_name_plural': 'продукты',
                'ordering': ('name',),
            },
        ),
    ]
