# Generated by Django 5.0.4 on 2024-04-22 07:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_date_of_creation_product_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name_category',), 'verbose_name': 'наименование_категории', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name_product',), 'verbose_name': 'наименование_продукта', 'verbose_name_plural': 'продукты'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='name_category',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='наименование_категории'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name_product',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='наименование_продукта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price_per_purchase',
            field=models.IntegerField(verbose_name='цена_за_покупку'),
        ),
    ]
