# Generated by Django 5.0.4 on 2024-04-22 07:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_date_of_creation_product_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufactured_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата_производства_продукта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price_per_purchase',
            field=models.IntegerField(verbose_name='цена_за_покупку'),
        ),
    ]
