# Generated by Django 5.0.4 on 2024-04-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='Description',
        ),
    ]
